openapi: 3.0.1
info:
  title: 'Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /api/Contractors:
    get:
      tags:
        - Contractors
      operationId: GetContractors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contractor'
    post:
      tags:
        - Contractors
      operationId: CreateContractor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContractorCommand'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - Contractors
      operationId: DeleteContractor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteContractorCommand'
      responses:
        '200':
          description: OK
  /api/Invoices:
    post:
      tags:
        - Invoices
      operationId: CreateInvoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvoiceCommand'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponseDto'
  /api/Orders:
    get:
      tags:
        - Orders
      operationId: GetOrders
      parameters:
        - name: dateFrom
          in: query
          required: true
          style: form
          schema:
            type: string
            format: date-time
        - name: dateTo
          in: query
          required: true
          style: form
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderDto'
components:
  schemas:
    Contractor:
      type: object
      properties:
        id:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        name:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        street:
          type: string
          nullable: true
        nip:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    CreateContractorCommand:
      type: object
      properties:
        name:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        nip:
          type: string
          nullable: true
        zipCode:
          type: string
          nullable: true
        street:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
      additionalProperties: false
    CreateInvoiceCommand:
      required:
        - orders
      type: object
      properties:
        invoiceNumber:
          type: integer
          format: int32
        saleDate:
          type: string
          format: date-time
        issueDate:
          type: string
          format: date-time
        orders:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/OrderDto'
        contractor:
          $ref: '#/components/schemas/Contractor'
      additionalProperties: false
    DeleteContractorCommand:
      required:
        - id
      type: object
      properties:
        id:
          minLength: 1
          type: string
      additionalProperties: false
    InvoiceResponseDto:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/ResponseDto'
      additionalProperties: false
    OrderDto:
      type: object
      properties:
        isSelected:
          type: boolean
        date:
          type: string
          format: date-time
        id:
          type: string
          nullable: true
        number:
          type: string
          nullable: true
        person:
          type: string
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
          nullable: true
        itemsCount:
          type: integer
          format: int32
          readOnly: true
        totalPrice:
          type: number
          format: double
          readOnly: true
      additionalProperties: false
    OrderItem:
      type: object
      properties:
        partNumber:
          type: string
          nullable: true
        partName:
          type: string
          nullable: true
        quantity:
          type: integer
          format: int32
        totalPrice:
          type: number
          format: double
      additionalProperties: false
    ResponseDto:
      type: object
      properties:
        kod:
          type: integer
          format: int32
        informacja:
          type: string
          nullable: true
      additionalProperties: false